Error in trial 3:
'val_loss'
